[package]
name = "blake3native"
version = "0.1.0"
authors = ["Hajime Yamaguchi <gen.yamaguchi0@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
blake3 = "0.1.1"
helix = "0.7.5"
hex = "0.3"
